import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ArrowRight,ArrowLeft,Check,CheckCircle2,ChevronRight,Download,Play,Plus,Radio,Square,Table2,Zap,Search,MousePointer2,Target,Pause,Settings2,Layers,History,ExternalLink,X,Copy,ShieldCheck,Upload,Command,Loader2,Globe,MoreHorizontal} from 'lucide-react';
import {parseCsv,csvResults} from './batch.js';
import identity from './identity.json';
import './panel.css';
const internal=!!globalThis.chrome?.runtime?.id;
const base=internal?identity.dashboardOrigin:location.origin;
const rpc=(path,body,method=body===undefined?'GET':'POST')=>new Promise((resolve,reject)=>{
 const rt=globalThis.chrome?.runtime;if(!rt?.sendMessage)return reject(Error('Open this page in Chrome with Mimic installed.'));
 const timer=setTimeout(()=>reject(Error('Mimic did not respond. Check Activity before trying again.')),path==='/state'?2500:45000);
 const callback=r=>{clearTimeout(timer);const error=rt.lastError;if(error||!r?.ok)reject(Error(r?.error||'Mimic is not connected to this browser.'));else resolve(r.data);};
 try{const message={channel:'mimic-v1',path,method,body};if(internal)rt.sendMessage(message,callback);else rt.sendMessage(identity.extensionId,message,callback);}catch(e){clearTimeout(timer);reject(e);}
});
const open=path=>internal?chrome.tabs.create({url:identity.dashboardOrigin+path}):window.open(base+path,'_blank','noopener');
const download=(text,name,type='text/csv')=>{const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const sampleCsv='title,link,shelf\nA new idea,https://example.com/idea,Ideas\nResearch notes,https://example.com/research,Research\nClass reading,https://example.com/class,School\n';
const host=url=>{try{return new URL(url).hostname}catch{return 'Website'}};
const time=iso=>iso?new Date(iso).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'';
const clean=c=>({name:c.name,description:c.description,parameters:c.parameters,steps:c.steps});
const statusLabel=s=>({passed:'Finished',failed:'Needs attention',interrupted:'Interrupted',cancelled:'Stopped',verified:'Verified',confirmed:'Confirmed by you',review:'Check this row',pending:'Waiting',running:'Running',paused:'Paused',completed:'Completed',ready:'Ready',skipped:'Skipped'}[s]||s);
function Brand(){return <span className="brand"><span className="brand-mark"><Command size={20}/></span>mimic<span className="brand-dot">•</span></span>;}
function Panel(){
 const [state,setState]=useState(null),[loaded,setLoaded]=useState(false),[account,setAccount]=useState({plan:'free'}),[view,setView]=useState('tasks'),[selected,setSelected]=useState(''),[batchId,setBatchId]=useState(''),[draftId,setDraftId]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[name,setName]=useState(''),[url,setUrl]=useState(''),[currentTab,setCurrentTab]=useState(null),[recordSource,setRecordSource]=useState('current'),[values,setValues]=useState({}),[mode,setMode]=useState('once'),[csv,setCsv]=useState(''),[mapping,setMapping]=useState({}),[parsed,setParsed]=useState(null),[typedList,setTypedList]=useState(false),[selector,setSelector]=useState(''),[expected,setExpected]=useState(''),[query,setQuery]=useState(''),[dismissed,setDismissed]=useState(''),[notice,setNotice]=useState(''),[connectionLost,setConnectionLost]=useState(false);
 const previousRecording=useRef(null),polling=useRef(false),locked=useRef(false),initialized=useRef(false);
 const refresh=async()=>{const next=await rpc('/state');setState(next);setConnectionLost(false);return next;};
 useEffect(()=>{let alive=true;const poll=async()=>{if(polling.current)return;polling.current=true;try{const s=await rpc('/state');if(alive){if(!initialized.current){setDismissed(s.runs.find(r=>r.kind!=='repair'&&!r.batchId)?.id||'');initialized.current=true;}setState(s);setConnectionLost(false);}}catch{if(alive)setConnectionLost(true);}finally{polling.current=false;if(alive)setLoaded(true);}};poll();rpc('/account').then(a=>{if(alive)setAccount(a)}).catch(()=>{});const t=setInterval(poll,1200);return()=>{alive=false;clearInterval(t);};},[]);
 useEffect(()=>{if(!state)return;const old=previousRecording.current;if(old&&!state.recording){const d=state.demonstrations.find(d=>d.id===old);if(d){setDraftId(d.id);setName(d.name);setView('draft');setSelected('');setBatchId('');}}previousRecording.current=state.recording?.id||null;},[state]);
 const act=async fn=>{if(locked.current)return;locked.current=true;setBusy(true);setError('');setNotice('');try{await fn();await refresh();}catch(e){setError(e.message);}finally{setBusy(false);locked.current=false;}};
 const command=state?.commands.find(c=>c.id===selected),batch=state?.batches?.find(b=>b.id===batchId),draft=state?.demonstrations.find(d=>d.id===draftId),active=state?.activeRun;
 const unavailable=busy||!!state?.recording||!!active||!!state?.batchActive||state?.busy||connectionLost;
 const modern=state?.version?.startsWith('4.');
 const last=state?.runs.find(r=>r.kind!=='repair'&&!r.batchId);
 const result=last&&!active&&last.finishedAt&&last.id!==dismissed?last:null;
 function navigate(next){setView(next);setSelected('');setBatchId('');setDraftId('');setError('');setNotice('');}
 function choose(c){navigate('tasks');setSelected(c.id);setValues(Object.fromEntries(c.parameters.map(p=>[p.key,p.default])));setCsv('');setParsed(null);setTypedList(false);setMapping({});setMode('once');setSelector(c.steps.at(-1)?.type==='assert'?c.steps.at(-1).selector:'');setExpected(c.steps.at(-1)?.type==='assert'?c.steps.at(-1).valueTemplate||c.steps.at(-1).value:'');}
 async function teach(){navigate('teach');setName('');setUrl('');setCurrentTab(null);setRecordSource(internal?'current':'url');if(internal){const t=await rpc('/tabs/current');setCurrentTab(t);if(!t)setRecordSource('url');}}
 function parse(text,source='csv'){const data=parseCsv(text);setTypedList(source==='typed');setParsed(data);setCsv(text);setMapping(Object.fromEntries(command.parameters.map(p=>[p.key,data.headers.find(h=>h.toLowerCase()===p.key.toLowerCase()||h.toLowerCase()===p.label.toLowerCase())||''])));}
 async function loadCsv(file){if(file.size>1000000)throw Error('Use a CSV smaller than 1 MB.');parse(await file.text());}
 async function saveCheck(){const steps=structuredClone(command.steps);if(steps.at(-1)?.type==='assert')steps.pop();steps.push({id:crypto.randomUUID(),type:'assert',label:'Check the visible result',selector,value:expected,...(expected.includes('{{')?{valueTemplate:expected}:{}),checkpoint:false,secret:false});await rpc(`/commands/${command.id}`,{...clean(command),steps},'PUT');setNotice('Success check saved.');}
 const saveTask=()=>act(async()=>{const c=await rpc('/learn',{demonstrationIds:[draft.id],name:name.trim()||draft.name});choose(c);setNotice('Task saved. Change the inputs below, then run it.');});
 if(!loaded)return <div className="loading"><Brand/><Loader2 className="spin"/><p>Connecting to your browser…</p></div>;
 if(!state)return <Welcome retry={()=>act(refresh)} busy={busy} error={error} internal={internal}/>;
 return <div className={`app-shell ${internal?'panel-shell':'web-shell'} ${state.runs.length?'returning':''}`}>
 <aside className="sidebar"><button className="brand-button" onClick={()=>navigate('tasks')} aria-label="Mimic home"><Brand/></button><span className="edition">YOUR PERSONAL REPEAT BUTTON</span><nav aria-label="Main navigation">{[['tasks',Layers,'My tasks'],['activity',History,'Activity'],['settings',Settings2,'Settings']].map(([key,Icon,label])=><button key={key} className={view===key?'selected':''} onClick={()=>navigate(key)}><Icon size={18}/><span>{label}</span>{key==='activity'&&(active||state.batchActive)&&<i className="live-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="connection"><i/> Chrome connected</div><button onClick={()=>open('/docs')}><ArrowUpRight size={16}/>Ideas & how-to guides</button><button onClick={()=>open('/practice')}><ArrowUpRight size={16}/>Practice playground</button><span>Less clicking. More living.</span></div></aside>
 <div className="workspace"><header className="topbar"><span className="desktop-label">{view==='teach'||view==='draft'?'TEACH A TASK':view==='activity'?'ACTIVITY':view==='settings'?'YOUR WORKSPACE':'MY TASKS'}</span><span className="connection"><i/>{connectionLost?'Reconnecting…':state.recording?'Recording':active?'Working':'Ready when you are'}</span><button className="icon-button" aria-label="Settings" onClick={()=>navigate('settings')}><Settings2 size={18}/></button></header>
 <main>
 {error&&<div className="notice error" role="alert"><div><b>Let’s fix that.</b><p>{error}</p></div><button className="icon-button" onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}
 {connectionLost&&<div className="notice error">Connection lost. Open Chrome’s extensions page and check that Mimic is enabled. Your saved tasks are still on this device.</div>}
 {notice&&<div className="notice success" role="status"><CheckCircle2 size={18}/>{notice}</div>}
 {!modern&&<div className="notice">Your Chrome extension needs the v4 update to use the new recording tools. <a href={`${base}/downloads/mimic-browser-companion.zip`}>Download update</a></div>}
 {state.recording&&<section className="session-card recording"><div className="session-heading"><span className="icon-tile orange"><Radio size={21}/></span><div><span className="eyebrow">{state.recording.status==='paused'?'PAUSED':'RECORDING NOW'}</span><h2>Show me once.</h2></div><span className="step-count">{state.recording.steps.length} steps</span></div><p>Do the task in your website tab. When you’re done, select the confirmation that proves it worked.</p><ol className="capture-steps">{state.recording.steps.slice(-4).map(s=><li key={s.id}><Check size={13}/><span>{s.label}</span>{s.type==='assert'&&<span className="tag green">Success</span>}</li>)}</ol><div className="actions"><button className="secondary" disabled={busy||!modern||state.recording.status==='paused'} onClick={()=>act(()=>rpc('/recordings/pick',{}))}><Target size={16}/>Pick success</button><button className="primary" disabled={busy} onClick={()=>act(()=>rpc('/recordings/stop',{}))}>Finish <Check size={16}/></button></div><div className="session-links"><button disabled={busy} onClick={()=>act(()=>rpc('/recordings/pause',{}))}>{state.recording.status==='paused'?<Play size={13}/>:<Pause size={13}/>} {state.recording.status==='paused'?'Resume recording':'Pause recording'}</button><button disabled={busy||!modern} onClick={()=>act(()=>rpc('/tab/focus',{}))}>Show website <ArrowUpRight size={13}/></button></div></section>}
 {active&&<section className={`session-card ${active.status==='paused'?'review':'running'}`} aria-live="polite"><div className="session-heading"><span className="icon-tile lime">{active.status==='paused'?<Pause size={20}/>:<Loader2 className="spin" size={20}/>}</span><div><span className="eyebrow">{active.status==='paused'?'YOUR TURN':'MIMIC IS WORKING'}</span><h2>{active.status==='paused'?'Ready for your review.':active.commandName}</h2></div></div><p>{active.message||active.steps[active.currentStep]?.label}</p><div className="progress-track"><div style={{width:`${Math.round(active.currentStep/active.steps.length*100)}%`}}/></div><div className="session-links"><span>Step {active.currentStep+1} of {active.steps.length}</span><button disabled={!modern} onClick={()=>act(()=>rpc('/tab/focus',{}))}>Show website <ArrowUpRight size={13}/></button></div><div className="actions">{active.status==='paused'&&<button className="primary" disabled={busy} onClick={()=>act(()=>rpc(`/runs/${active.id}/continue`,{}))}>Continue this step <ArrowRight size={16}/></button>}<button className="text-button" disabled={busy} onClick={()=>act(()=>rpc(`/runs/${active.id}/cancel`,{}))}><Square size={12}/>Stop run</button></div></section>}
 {result&&!batch&&view==='tasks'&&<RunResult run={result} dismiss={()=>setDismissed(result.id)} choose={()=>{const c=state.commands.find(c=>c.id===result.commandId);if(c)choose(c);}}/>}
 {view==='tasks'&&!command&&<>
 <section className="hero"><div><span className="eyebrow"><span className="tiny-star">✳</span> FOR YOUR EVERYDAY INTERNET</span><h1>Your clicks.<br/><span>On repeat.</span></h1><p>Show Mimic a little task you do online.<br/>Next time, change the details and let it repeat the steps.</p><button className="primary" disabled={unavailable||!modern} onClick={()=>act(teach)}><Plus size={17}/>Teach a task</button></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="art-card source"><MousePointer2 size={17}/><span>You show it once.</span><span className="mini-dot"/></div><div className="art-engine"><Command size={42}/></div><div className="art-card done"><CheckCircle2 size={17}/><span>One less thing to do.</span></div><span className="art-spark spark-one">✳</span><span className="art-spark spark-two">+</span></div></section>
 <button className="quickstart" disabled={unavailable||!modern} onClick={()=>act(()=>rpc('/quickstart',{}))}><span className="play-orb"><Play size={18} fill="currentColor"/></span><span><b>See it actually work</b><small>Watch Mimic save a reading and check that it worked. No setup.</small></span><ArrowUpRight size={21}/></button>
 <div className="guide-callout"><div><b>What would you like to make easier?</b><p>Save good reads, collect trip ideas, or keep a wishlist.</p></div><button className="text-button" onClick={()=>open('/docs')}>Open the guide <ArrowUpRight size={15}/></button></div><div className="section-heading"><div><h2>Ready to repeat <span>{state.commands.length}</span></h2><p>Your tasks live in this Chrome profile.</p></div></div>
 {state.commands.length>3&&<label className="search"><Search size={17}/><input aria-label="Search tasks" placeholder="Find a task…" value={query} onChange={e=>setQuery(e.target.value)}/></label>}
 <div className="task-grid">{state.commands.filter(c=>(c.name+' '+c.description).toLowerCase().includes(query.toLowerCase())).map(c=><button className="task-card" key={c.id} onClick={()=>choose(c)}><div className="task-card-top"><span className={`icon-tile ${c.sample?'lavender':'peach'}`}>{c.sample?<Zap size={21}/>:<MousePointer2 size={21}/>}</span><span className="tag">{c.sample?'Practice':host(c.steps[0]?.url)}</span><ArrowUpRight size={17}/></div><h3>{c.name}</h3><p>{c.parameters.length} editable inputs <span>·</span> {c.steps.length} steps</p><div className="task-card-bottom"><span>{c.steps.at(-1)?.type==='assert'?<><Target size={13}/>Success check included</>:<><Layers size={13}/>Saved workflow</>}</span><ChevronRight size={16}/></div></button>)}{state.commands.filter(c=>(c.name+' '+c.description).toLowerCase().includes(query.toLowerCase())).length===0&&<div className="empty"><Search size={25}/><h3>No tasks found.</h3><p>Try a different search or teach a new task.</p></div>}</div>
 {state.demonstrations.some(d=>!d.commandId)&&<section className="drafts"><div className="section-heading"><h2>Finish teaching</h2><span className="muted">Saved drafts</span></div>{state.demonstrations.filter(d=>!d.commandId).slice(0,5).map(d=><button className="list-item" key={d.id} onClick={()=>{navigate('draft');setDraftId(d.id);setName(d.name);}}><span className="icon-tile"><Radio size={17}/></span><span><b>{d.name}</b><small>{d.steps.length} captured steps</small></span><ChevronRight size={17}/></button>)}</section>}
 </>}
 {view==='teach'&&!state.recording&&<div className="narrow"><button className="back" onClick={()=>navigate('tasks')}><ArrowLeft size={16}/>My tasks</button><span className="eyebrow orange-text">TEACH → CHECK → REPEAT</span><h1>Just do your thing.</h1><p className="lead">Mimic watches the clicks and inputs in one tab. You stay in control.</p><form className="surface" onSubmit={e=>{e.preventDefault();act(async()=>{const taskName=name.trim()||'My new task';if(recordSource==='current'&&currentTab)await rpc('/recordings/current',{name:taskName,tabId:currentTab.id});else await rpc('/recordings',{name:taskName,url});});}}>
 <label>Give this task a name<input autoFocus value={name} onChange={e=>setName(e.target.value)} maxLength={100} placeholder="e.g. Save something to my reading list"/></label>
 {currentTab&&<div className="segmented"><button type="button" className={recordSource==='current'?'active':''} onClick={()=>setRecordSource('current')}>Current tab</button><button type="button" className={recordSource==='url'?'active':''} onClick={()=>setRecordSource('url')}>Another website</button></div>}
 {recordSource==='current'&&currentTab?<div className="website-chip"><Globe size={20}/><div><b>{currentTab.title}</b><small>{host(currentTab.url)}</small></div><button type="button" className="text-button" onClick={()=>act(async()=>{const t=await rpc('/tabs/current');setCurrentTab(t);if(!t)setRecordSource('url');})}>Refresh</button></div>:<label>Website to open<input required type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://your-website.com"/></label>}
 <div className="how-to"><div><span>1</span><p><b>Do the task as usual.</b> Click, type, and save.</p></div><div><span>2</span><p><b>Pick the success message.</b> Click the result on the page.</p></div><div><span>3</span><p><b>Finish and save your task.</b> The inputs become reusable.</p></div></div><button className="primary wide" disabled={unavailable||!modern}><Radio size={17}/>Start recording</button><p className="fine-print">Only the selected tab is recorded. Passwords become manual steps. Chrome shows a debugging banner while Mimic is connected.</p></form></div>}
 {view==='draft'&&draft&&!state.recording&&<div className="narrow"><button className="back" onClick={()=>navigate('tasks')}><ArrowLeft size={16}/>Save for later</button><span className="eyebrow orange-text">ONE LAST LOOK</span><h1>You taught it.</h1><p className="lead">Review the steps, then make this a task you can use again.</p><section className="surface"><label>Task name<input value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></label><StepList steps={draft.steps}/>{draft.warnings.map(w=><p className="notice" key={w}>{w}</p>)}<div className={`outcome-summary ${draft.steps.at(-1)?.type==='assert'?'good':''}`}><Target size={19}/><div><b>{draft.steps.at(-1)?.type==='assert'?'Success check captured':'No success check yet'}</b><p>{draft.steps.at(-1)?.type==='assert'?draft.steps.at(-1).value:'You can run this task one at a time. For lists, record again and use Pick success before finishing.'}</p></div></div><button className="primary wide" disabled={unavailable||draft.steps.length<2} onClick={saveTask}>Save task <ArrowRight size={17}/></button></section></div>}
 {command&&<>
 <button className="back" onClick={()=>navigate('tasks')}><ArrowLeft size={16}/>My tasks</button><div className="detail-heading"><span className="icon-tile peach"><MousePointer2 size={22}/></span><div><span className="eyebrow">{host(command.steps[0]?.url)}</span><h1>{command.name}</h1></div></div>
 <div className="detail-layout"><div><div className="segmented run-modes"><button className={mode==='once'?'active':''} onClick={()=>setMode('once')}><Play size={15}/>Run once</button><button className={mode==='list'?'active':''} onClick={()=>setMode('list')}><Table2 size={15}/>Run a list</button></div>
 {mode==='once'?<section className="surface"><h2>What’s different this time?</h2><p className="muted">Change the inputs. Mimic handles the steps.</p>{command.parameters.map(p=><label key={p.key}>{p.label}{p.examples.length>1&&command.steps.some(s=>s.parameter===p.key&&s.type==='select')?<select value={values[p.key]??p.default} onChange={e=>setValues({...values,[p.key]:e.target.value})}>{[...new Set([p.default,...p.examples,values[p.key]])].filter(v=>v!==undefined).map(v=><option key={v}>{v}</option>)}</select>:<input value={values[p.key]??p.default} onChange={e=>setValues({...values,[p.key]:e.target.value})}/>}</label>)}{!command.parameters.length&&<p>This task has no changing inputs.</p>}<button className="primary wide" disabled={unavailable} onClick={()=>act(()=>rpc(`/commands/${command.id}/run`,{values,mode:'run'}))}><Play size={16}/>Run task</button><button className="text-button wide" disabled={unavailable} onClick={()=>act(()=>rpc(`/commands/${command.id}/run`,{values,mode:'test'}))}>Or review every action first <ArrowRight size={14}/></button><p className="fine-print">Saved review checkpoints still pause the task before an action.</p></section>:<section className="surface"><h2>One task. Your whole list.</h2><p className="muted">Type the things you want to repeat. Mimic checks each result before moving on.</p>{command.steps.at(-1)?.type!=='assert'?<div className="notice"><Target size={19}/><div><b>Add a success check first.</b><p>Open Task details below to set the expected result, or record the task again and choose Pick success.</p></div></div>:<>
 <ListEntry key={command.id} command={command} disabled={unavailable} limit={account.plan==='pro'?100:3} onEdit={()=>{setParsed(null);setCsv('');}} onPreview={text=>act(()=>parse(text,'typed'))}/>
 <details className="csv-import"><summary>Import a CSV file instead</summary><label className="upload"><Upload size={26}/><b>Drop in a CSV file</b><span>or click to choose · up to {account.plan==='pro'?100:3} rows</span><input type="file" accept=".csv,text/csv" aria-label="Upload batch CSV" disabled={unavailable} onChange={e=>{const f=e.target.files?.[0];if(f)act(()=>loadCsv(f));e.target.value='';}}/></label></details>{command.sample&&<button className="text-button wide" disabled={unavailable} onClick={()=>act(()=>parse(sampleCsv))}><Zap size={14}/>Use 3 example rows</button>}
 <details className="paste-data"><summary>Or paste CSV from a spreadsheet</summary><textarea aria-label="Paste CSV" value={csv} onChange={e=>{setCsv(e.target.value);setParsed(null);}} placeholder={'title,link,shelf\nA good read,https://example.com/article,Ideas'}/><button disabled={!csv.trim()||unavailable} onClick={()=>act(()=>parse(csv))}>Use these rows</button></details>
 {parsed&&<><div className="section-heading"><h3>{parsed.rows.length} items ready</h3><span className="tag green">{typedList?'Ready to go':command.parameters.every(p=>mapping[p.key])?'Columns matched':'Match columns'}</span></div>{!typedList&&command.parameters.map(p=><label className="mapping" key={p.key}><span>{p.label}</span><ArrowRight size={14}/><select value={mapping[p.key]||''} onChange={e=>setMapping({...mapping,[p.key]:e.target.value})}><option value="">Choose a column</option>{parsed.headers.map(h=><option key={h}>{h}</option>)}</select></label>)}<div className="table-scroll"><table><thead><tr>{parsed.headers.map(h=><th key={h}>{typedList?command.parameters.find(p=>p.key===h)?.label||h:h}</th>)}</tr></thead><tbody>{parsed.rows.slice(0,3).map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div><button className="primary wide" disabled={unavailable||command.parameters.some(p=>!mapping[p.key])} onClick={()=>act(async()=>{const b=await rpc('/batches',{commandId:command.id,csv,mapping});navigate('activity');setBatchId(b.id);})}>Review batch <ArrowRight size={16}/></button></>}
 </>}</section>}
 </div><aside className="task-context"><section className="context-card"><span className="eyebrow">WHAT MIMIC WILL DO</span><StepList steps={command.steps}/><div className={`outcome-summary ${command.steps.at(-1)?.type==='assert'?'good':''}`}><Target size={18}/><div><b>{command.steps.at(-1)?.type==='assert'?'Checks the result':'Actions recorded'}</b><p>{command.steps.at(-1)?.type==='assert'?'A visible page result must match before the task passes.':'Add an outcome check before using this task for lists.'}</p></div></div></section>
 <details className="surface advanced"><summary><Settings2 size={16}/>Task details</summary><label>Task name<input defaultValue={command.name} key={command.id+command.name} maxLength={100} onBlur={e=>{if(e.target.value.trim()&&e.target.value.trim()!==command.name)act(()=>rpc(`/commands/${command.id}`,{...clean(command),name:e.target.value.trim()},'PUT'));}}/></label><h3>Success check</h3><label>Page element (CSS selector)<input value={selector} onChange={e=>setSelector(e.target.value)} placeholder="#confirmation"/></label><label>Text to expect<input value={expected} onChange={e=>setExpected(e.target.value)} placeholder="Saved"/></label><p className="fine-print">Input placeholders such as {'{{title}}'} update with each row.</p><button disabled={unavailable||!selector.trim()||!expected.trim()} onClick={()=>act(saveCheck)}>Save success check</button><h3>Pause before these actions</h3>{command.steps.filter(s=>['click','press','check'].includes(s.type)).map(s=><label className="checkbox" key={s.id}><input type="checkbox" aria-label={`Review before ${s.label}`} checked={s.checkpoint} disabled={unavailable} onChange={e=>act(()=>rpc(`/commands/${command.id}`,{...clean(command),steps:command.steps.map(x=>x.id===s.id?{...x,checkpoint:e.target.checked}:x)},'PUT'))}/>{s.label}</label>)}<button className="text-button" onClick={()=>act(async()=>download(JSON.stringify(await rpc(`/commands/${command.id}/export`),null,2),`${command.name}.json`,'application/json'))}><Download size={15}/>Export task</button><button className="text-button" onClick={()=>open('/studio')}>Edit steps in advanced studio <ArrowUpRight size={14}/></button></details></aside></div>
 </>}
 {view==='activity'&&!batch&&<><div className="page-heading"><span className="eyebrow orange-text">THE RECEIPTS</span><h1>See what happened.</h1><p>Every run, every result. Pick one to see what happened.</p></div>{!state.runs.length&&!state.batches.length&&<div className="empty"><History size={34}/><h3>Your first result goes here.</h3><p>Try the practice task to watch a real run.</p><button className="primary" disabled={unavailable||!modern} onClick={()=>act(async()=>{navigate('tasks');await rpc('/quickstart',{});})}>See Mimic work <Play size={14}/></button></div>}
 {state.batches.length>0&&<><h2>Lists</h2><div className="activity-list">{state.batches.map(b=><button className="list-item" key={b.id} onClick={()=>setBatchId(b.id)}><span className="icon-tile lavender"><Table2 size={19}/></span><span><b>{b.name}</b><small>{b.rows.filter(r=>r.status==='verified').length} of {b.rows.length} rows verified</small></span><span className={`tag ${b.status==='completed'?'green':''}`}>{statusLabel(b.status)}</span><ChevronRight size={16}/></button>)}</div></>}
 {state.runs.filter(r=>!r.batchId).length>0&&<><h2>Single runs</h2><div className="activity-list">{state.runs.filter(r=>!r.batchId).slice(0,30).map(r=><details className="run-history" key={r.id}><summary><span className={`result-icon ${r.status==='passed'?'good':'attention'}`}>{r.status==='passed'?<Check size={18}/>:<History size={18}/>}</span><span><b>{r.commandName}</b><small>{time(r.startedAt)} · {statusLabel(r.status)}</small></span><ChevronRight size={16}/></summary><div className="run-history-body">{r.outputs.map((o,i)=><p className="proof" key={i}>{o.text}</p>)}{r.error&&<p className="notice error">{r.error}</p>}<StepList steps={r.steps}/></div></details>)}</div></>}
 </>}
 {batch&&<><button className="back" onClick={()=>setBatchId('')}><ArrowLeft size={16}/>Activity</button><div className="page-heading"><span className={`tag ${batch.status==='completed'?'green':''}`}>{statusLabel(batch.status)}</span><h1>{batch.name}</h1><p>One row at a time. A checked result before the next.</p></div><section className="surface batch-overview"><div className="batch-number"><strong>{batch.rows.filter(r=>r.status==='verified').length}<span>/{batch.rows.length}</span></strong><p>rows verified on the website</p></div><div className="progress-track"><div style={{width:`${batch.rows.filter(r=>r.status==='verified').length/batch.rows.length*100}%`}}/></div>{batch.error&&<p className="notice">{batch.error}</p>}<div className="actions">{state.batchActive===batch.id?<button disabled={busy} onClick={()=>act(()=>rpc(`/batches/${batch.id}/stop`,{}))}><Pause size={15}/>Stop after this row</button>:batch.rows.some(r=>r.status==='pending')&&<button className="primary" disabled={unavailable||batch.rows.some(r=>r.status==='review')} onClick={()=>act(()=>rpc(`/batches/${batch.id}/start`,{}))}><Play size={15}/>{batch.status==='ready'?'Start batch':'Continue pending rows'}</button>}<button className="secondary" onClick={()=>download(csvResults(batch),'mimic-results.csv')}><Download size={15}/>Export results</button></div>{batch.rows.some(r=>r.status==='review')&&<p className="fine-print">Check the uncertain row on the website and add a note below. Mimic won’t repeat a possible submission automatically.</p>}</section><div className="batch-rows">{batch.rows.map((r,i)=><Row key={r.id} row={r} index={i} busy={busy||!!state.batchActive} resolve={(decision,note)=>act(()=>rpc(`/batches/${batch.id}/resolve`,{rowId:r.id,decision,note}))}/>)}</div></>}
 {view==='settings'&&<div className="narrow"><div className="page-heading"><span className="eyebrow orange-text">MAKE YOURSELF AT HOME</span><h1>Make it yours.</h1></div><section className="surface"><div className="section-heading"><h2>Mimic {state.version}</h2><span className="tag green">Connected</span></div><p>Tasks and recordings stay in this Chrome profile. An account is optional for local tasks.</p><div className="settings-actions"><button className="secondary" onClick={()=>open('/docs')}>Ideas & how-to guides <ArrowUpRight size={16}/></button><button className="secondary" onClick={()=>act(async()=>download(JSON.stringify(await rpc('/backup'),null,2),'mimic-backup.json','application/json'))}><Download size={16}/>Back up my library</button><button className="secondary" onClick={()=>open('/account')}>My account <ArrowUpRight size={16}/></button><button className="secondary" onClick={()=>open('/studio')}>Advanced studio <ArrowUpRight size={16}/></button><button className="text-button" onClick={()=>open('/privacy')}>Privacy & permissions <ArrowUpRight size={14}/></button></div></section><section className="surface"><h2>Keep Mimic beside your work.</h2><p>In Chrome, pin Mimic from the puzzle-piece menu. Click its icon to open this workspace as a side panel.</p><p className="fine-print">The unpacked extension must stay in its installed folder. Replacing its files and clicking Reload preserves your tasks; removing the extension deletes its local library.</p></section><p className="fine-print">Free includes 3 custom tasks and 3 rows per list. {account.plan==='pro'?'Your Pro plan is connected.':'Paid checkout is still being prepared.'}</p></div>}
 </main><footer><span><ShieldCheck size={13}/>On your device. Under your control.</span><div className="footer-links"><button onClick={()=>open('/docs')}>Guide & docs</button><button onClick={()=>open('/privacy')}>Privacy</button></div></footer>
 </div></div>;
}
function ListEntry({command,disabled,limit,onEdit,onPreview}){
 const defaults=()=>Object.fromEntries(command.parameters.map(p=>[p.key,p.default]));
 const [items,setItems]=useState(()=>[{id:crypto.randomUUID(),values:defaults()}]);
 const edit=(id,key,value)=>{setItems(rows=>rows.map(row=>row.id===id?{...row,values:{...row.values,[key]:value}}:row));onEdit();};
 const changeRows=rows=>{setItems(rows);onEdit();};
 const preview=()=>{const cell=value=>'"'+String(value??'').replaceAll('"','""')+'"';const keys=command.parameters.map(p=>p.key);onPreview([keys,...items.map(row=>keys.map(key=>row.values[key]))].map(row=>row.map(cell).join(',')).join('\r\n'));};
 if(!command.parameters.length)return <p className="fine-print">This task has no editable details. Run it once, or use CSV import for a repeated task you have reviewed.</p>;
 return <div className="list-entry"><div className="section-heading"><h3>Your items</h3><span className="tag">{items.length} / {limit}</span></div>{items.map((row,index)=><fieldset key={row.id} disabled={disabled}><legend>Item {index+1}</legend><div className="item-heading"><span>Change the details for this item.</span>{items.length>1&&<button type="button" className="icon-button" aria-label={`Remove item ${index+1}`} onClick={()=>changeRows(items.filter(item=>item.id!==row.id))}><X size={15}/></button>}</div>{command.parameters.map(p=><label key={p.key}>{p.label}{p.examples.length>1&&command.steps.some(step=>step.parameter===p.key&&step.type==='select')?<select aria-label={`Item ${index+1}: ${p.label}`} value={row.values[p.key]??p.default} onChange={e=>edit(row.id,p.key,e.target.value)}>{[...new Set([p.default,...p.examples,row.values[p.key]])].filter(v=>v!==undefined).map(value=><option key={value}>{value}</option>)}</select>:<input aria-label={`Item ${index+1}: ${p.label}`} value={row.values[p.key]??''} maxLength={12000} onChange={e=>edit(row.id,p.key,e.target.value)}/>}</label>)}</fieldset>)}<div className="actions"><button className="secondary" disabled={disabled||items.length>=limit} onClick={()=>changeRows([...items,{id:crypto.randomUUID(),values:defaults()}])}><Plus size={15}/>Add another item</button><button className="primary" disabled={disabled||items.length>limit} onClick={preview}>Preview my list <ArrowRight size={15}/></button></div><p className="fine-print">Nothing runs until you review and start the list. Use the same choices your recorded website accepts.</p></div>;
}
function StepList({steps}){return <ol className="step-list">{steps.map((s,i)=><li key={s.id}><span className={`step-number ${s.type==='assert'?'check-number':''}`}>{s.type==='assert'?<Check size={12}/>:i+1}</span><div><b>{s.label}</b>{s.parameter&&<small>Uses your input</small>}{s.checkpoint&&<small>Pauses for your review</small>}{s.type==='assert'&&s.value&&<small>{s.valueTemplate||s.value}</small>}</div>{s.status&&<span className={s.status==='passed'?'green-text':'muted'}>{s.status==='passed'?<Check size={13}/>:statusLabel(s.status)}</span>}</li>)}</ol>;}
function RunResult({run,dismiss,choose}){const good=run.status==='passed';return <section className={`result-card ${good?'good':'attention'}`} role="status"><div className="session-heading"><span className="result-icon">{good?<CheckCircle2 size={24}/>:<Pause size={22}/>}</span><div><span className="eyebrow">{good?'DONE, WITH A RECEIPT':'STOPPED HERE'}</span><h2>{good?'That’s one less thing.':'This needs a look.'}</h2></div><button className="icon-button" onClick={dismiss} aria-label="Dismiss result"><X size={17}/></button></div><p>{run.commandName} · {run.steps.filter(s=>s.status==='passed').length}/{run.steps.length} steps completed</p>{[...new Map(run.outputs.map(o=>[o.text,o])).values()].map((o,i)=><p className="proof" key={i}>{o.text}</p>)}{run.error&&<p className="proof">{run.error}</p>}<button className="text-button" onClick={choose}>{good?'Use different inputs':'Review task'}<ArrowRight size={14}/></button></section>;}
function Row({row,index,resolve,busy}){const [note,setNote]=useState('');return <section className={`row-result ${row.status}`}><div className="row-heading"><span className="row-index">{row.status==='verified'?<Check size={16}/>:index+1}</span><b>{Object.values(row.values)[0]||`Row ${index+1}`}</b><span className={`tag ${row.status==='verified'?'green':''}`}>{statusLabel(row.status)}</span></div><details><summary>Inputs & observed result</summary><dl>{Object.entries(row.values).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{row.output&&<p className="proof">{row.output}</p>}</details>{row.note&&<p className="small">{row.note}</p>}{row.status==='review'&&<><label>What did you find on the website?<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={500} placeholder="I checked the record and…"/></label><div className="actions"><button disabled={busy||note.trim().length<5} onClick={()=>resolve('confirmed',note)}>Confirm with my note</button><button disabled={busy||note.trim().length<5} onClick={()=>resolve('skip',note)}>Skip this row</button></div></>}</section>;}
function Welcome({retry,busy,error,internal}){const [step,setStep]=useState(0),[copied,setCopied]=useState(false);return <div className="welcome"><header><Brand/><nav className="welcome-nav" aria-label="Site navigation"><a href={base+'/docs'}>Guide & docs <ArrowUpRight size={14}/></a><a href={base+'/privacy'}>Privacy <ArrowUpRight size={14}/></a></nav></header><main><div className="welcome-copy"><span className="eyebrow orange-text">FOR YOUR EVERYDAY INTERNET</span><h1>Less clicking.<br/><span>More living.</span></h1><p>Reading lists. Trip ideas. Things you want to save for later. Show Mimic a browser task once, then let it repeat the steps with new details.</p><div className="welcome-pills"><span><MousePointer2 size={15}/>Teach by doing</span><span><Table2 size={15}/>Run a whole list</span><span><Target size={15}/>Verify the result</span></div><button className="primary" onClick={()=>{setStep(1);document.getElementById('install').scrollIntoView({behavior:'smooth'});}}>Set up in Chrome <ArrowRight size={17}/></button><p className="fine-print">Free to try. No coding or spreadsheet needed.</p></div><div className="preview-board"><div className="preview-title"><span className="mini-dot"/> THE IDEA IN 3 STEPS <span>EXAMPLE</span></div><div className="preview-row"><span className="preview-count">01</span><div><small>YOU SHOW IT</small><b>Save a good read</b><p>Add title → paste link → save</p></div><MousePointer2 size={24}/></div><div className="connector-line"/><div className="preview-row"><span className="preview-count">02</span><div><small>YOU GIVE IT THE INPUTS</small><b>More things worth keeping.</b><div className="mini-table"><span>A weekend idea</span><span>Ideas</span><span>A good article</span><span>Research</span></div></div><Table2 size={24}/></div><div className="connector-line"/><div className="preview-row preview-success"><CheckCircle2 size={27}/><div><small>MIMIC CHECKS THE PAGE</small><b>A result you can point to.</b><p>See what saved, and what needs a look.</p></div></div><span className="board-caption">An example of a task you can teach. Try the real reading demo.</span></div>
 <section id="install" className="install-card"><div><span className="eyebrow orange-text">A QUICK, ONE-TIME SETUP</span><h2>{internal?'Reconnect your workspace.':'Make Chrome your extra pair of hands.'}</h2><p>{internal?'Check that Mimic is enabled in Chrome’s extensions page, then reconnect.':'Mimic is currently installed as an unpacked Chrome extension. Keep its folder somewhere permanent.'}</p></div><div className="install-steps"><div><span>1</span><div><b>Download and unzip Mimic</b><p>Keep the extracted mimic-browser-companion folder.</p><a className="secondary" href={base+'/downloads/mimic-browser-companion.zip'} download onClick={()=>setStep(2)}><Download size={16}/>Download extension</a></div></div><div className={step>=2?'highlight':''}><span>2</span><div><b>Load it in Chrome</b><p>Open <code>chrome://extensions</code>. Turn on <strong>Developer mode</strong>, click <strong>Load unpacked</strong>, and select that folder.</p><button className="text-button" onClick={async()=>{try{await navigator.clipboard.writeText('chrome://extensions');setCopied(true);}catch{setCopied(false);}}}><Copy size={13}/>{copied?'Copied':'Copy extensions address'}</button></div></div><div><span>3</span><div><b>You’re in. Click “See it actually work.”</b><p>This page connects automatically in the same Chrome profile. Pin Mimic for the side panel.</p><button className="primary" disabled={busy} onClick={retry}>{busy?<Loader2 className="spin" size={15}/>:<Zap size={15}/>}Connect Mimic</button></div></div></div>{error&&<p role="alert" className="notice error">{error}</p>}</section></main><footer>Browser tasks stay in your Chrome profile. Review checkpoints keep you in control.<a href={base+'/docs'}>Ideas & how-to guides <ArrowUpRight size={13}/></a></footer></div>;}
createRoot(document.getElementById('root')).render(<Panel/>);
