import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,Check,ChevronLeft,Download,Layers,Play,Plus,Radio,ShieldCheck,Square,Table2,Zap} from 'lucide-react';
import {parseCsv,csvResults} from './batch.js';
import identity from './identity.json';
import './panel.css';
const rpc=(path,body,method=body===undefined?'GET':'POST')=>new Promise((resolve,reject)=>chrome.runtime.sendMessage({channel:'mimic-v1',path,method,body},r=>{const error=chrome.runtime.lastError;if(error||!r?.ok)reject(Error(r?.error||error?.message||'Mimic is not responding.'));else resolve(r.data);}));
const open=path=>chrome.tabs.create({url:identity.dashboardOrigin+path});
const download=(text,name,type='text/csv')=>{const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function Panel(){
 const [state,setState]=useState(null),[account,setAccount]=useState({plan:'free'}),[tab,setTab]=useState('workflows'),[selected,setSelected]=useState(''),[batchId,setBatchId]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[record,setRecord]=useState(false),[name,setName]=useState(''),[url,setUrl]=useState(''),[values,setValues]=useState({}),[csv,setCsv]=useState(''),[mapping,setMapping]=useState({}),[parsed,setParsed]=useState(null),[selector,setSelector]=useState(''),[expected,setExpected]=useState('');
 const refresh=async()=>setState(await rpc('/state'));
 useEffect(()=>{refresh().catch(e=>setError(e.message));rpc('/account').then(setAccount).catch(()=>{});const timer=setInterval(()=>refresh().catch(()=>{}),800);return()=>clearInterval(timer);},[]);
 const act=async(fn)=>{setBusy(true);setError('');try{await fn();await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const command=state?.commands.find(c=>c.id===selected),batch=state?.batches?.find(b=>b.id===batchId),active=state?.activeRun;
 const unavailable=busy||!!state?.recording||!!active||!!state?.batchActive||state?.busy;
 function choose(c){setSelected(c.id);setValues(Object.fromEntries(c.parameters.map(p=>[p.key,p.default])));setCsv('');setParsed(null);setMapping({});setSelector(c.steps.at(-1)?.type==='assert'?c.steps.at(-1).selector:'');setExpected(c.steps.at(-1)?.type==='assert'?c.steps.at(-1).value:'');}
 async function loadCsv(file){if(file.size>1000000)throw Error('Use a CSV smaller than 1 MB.');const text=await file.text(),data=parseCsv(text);setParsed(data);setCsv(text);setMapping(Object.fromEntries(command.parameters.map(p=>[p.key,data.headers.find(h=>h.toLowerCase()===p.key.toLowerCase()||h.toLowerCase()===p.label.toLowerCase())||''])));}
 async function saveCheck(){const steps=structuredClone(command.steps);if(steps.at(-1)?.type==='assert')steps.pop();steps.push({id:crypto.randomUUID(),type:'assert',label:'Verify the result',selector,value:expected,checkpoint:false,secret:false});await rpc(`/commands/${command.id}`,{name:command.name,description:command.description,parameters:command.parameters,steps},'PUT');}
 if(!state)return <main><p>Opening your workspace…</p>{error&&<p role="alert">{error}</p>}</main>;
 return <><header><button className="brand" onClick={()=>{setSelected('');setBatchId('');}}><span className="logo">m</span>mimic<span className="version">3</span></button><button className="plan" onClick={()=>open('/account')}>{account.plan==='pro'?'PRO':'FREE'} <ArrowUpRight size={13}/></button></header>
 <div className="intro"><span className="eyebrow"><i/> YOUR BROWSER. LESS BUSYWORK.</span><h1>Teach once.<br/><em>Get your time back.</em></h1><p>Turn a workflow into a repeatable command, then put your spreadsheet to work.</p></div>
 <nav>{[['workflows',Layers,'Workflows'],['batches',Table2,'Batches']].map(([key,Icon,label])=><button className={tab===key?'chosen':''} key={key} onClick={()=>{setTab(key);setSelected('');setBatchId('');}}><Icon size={15}/>{label}</button>)}</nav>
 <main>{error&&<div className="notice error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss">×</button></div>}
 {state.recording&&<section className="live"><b><Radio size={16}/> Recording: {state.recording.name}</b><p>{state.recording.steps.length} steps captured. Password fields become manual steps.</p><div className="actions"><button disabled={busy} onClick={()=>act(()=>rpc('/recordings/pause',{}))}>{state.recording.status==='paused'?'Resume':'Pause capture'}</button><button className="primary" disabled={busy} onClick={()=>act(()=>rpc('/recordings/stop',{}))}>Finish recording</button></div></section>}
 {active&&<section className="live"><b><span className="pulse"/>{active.status==='paused'?'Your review is needed':'Running workflow'}</b><p>{active.message||active.steps[active.currentStep]?.label}</p><progress max={active.steps.length} value={active.currentStep}/><div className="actions">{active.status==='paused'&&<button className="primary" disabled={busy} onClick={()=>act(()=>rpc(`/runs/${active.id}/continue`,{}))}>Continue this step</button>}<button disabled={busy} onClick={()=>act(()=>rpc(`/runs/${active.id}/cancel`,{}))}><Square size={13}/>Cancel run</button></div></section>}
 {tab==='workflows'&&!command&&<><div className="section-head"><h2>Your shortcuts <span>{state.commands.length}</span></h2><button className="icon" disabled={unavailable} aria-label="Record workflow" onClick={()=>{setRecord(!record);setUrl(state.practiceUrl);}}><Plus size={20}/></button></div>
 {record&&<form className="card" onSubmit={e=>{e.preventDefault();act(async()=>{await rpc('/recordings',{name,url});setRecord(false);});}}><h3>Show Mimic how it’s done</h3><label>Workflow name<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="Add a lead to my CRM"/></label><label>Starting website<input required type="url" value={url} onChange={e=>setUrl(e.target.value)}/></label><button className="primary" disabled={unavailable}><Radio size={15}/>Open tab & record</button><p className="small">Record in the tab Mimic opens. Use Option / Alt + click to capture result text. Review every step before running.</p></form>}
 {state.commands.map(c=><button className="workflow" key={c.id} onClick={()=>choose(c)}><span className="tile"><Zap size={19}/></span><span><b>{c.name}</b><small>{c.sample?'PRACTICE · ':''}{c.steps.length} steps · {c.parameters.length} inputs</small></span><ArrowUpRight size={16}/></button>)}
 <section className="tip"><ShieldCheck size={19}/><div><b>Start with the practice workflow.</b><p>Run a test, review the save step, and see a real confirmation. Nothing leaves your browser.</p></div></section>
 {state.demonstrations.filter(d=>!d.commandId).slice(0,5).map(d=><section className="card" key={d.id}><span className="eyebrow">READY TO REVIEW</span><h3>{d.name}</h3><details><summary>{d.steps.length} captured steps</summary>{d.steps.map((s,i)=><p className="small" key={s.id}>{i+1}. {s.label}{s.checkpoint?' · review checkpoint':''}</p>)}{d.warnings.map(w=><p className="notice" key={w}>{w}</p>)}</details><button disabled={unavailable||d.steps.length<2} onClick={()=>act(async()=>{const c=await rpc('/learn',{demonstrationIds:[d.id],name:d.name});choose(c);})}>Create workflow</button></section>)}
 <button className="wide" onClick={()=>open('/')}><ArrowUpRight size={15}/>Advanced editor & all workspaces</button></>}
 {command&&<><button className="back" onClick={()=>setSelected('')}><ChevronLeft size={15}/>All workflows</button><h2>{command.name}</h2><p className="muted">{command.description}</p><section className="card"><span className="eyebrow">01 / TRY A SINGLE ROW</span>{command.parameters.map(p=><label key={p.key}>{p.label}<input value={values[p.key]??p.default} onChange={e=>setValues({...values,[p.key]:e.target.value})}/></label>)}<div className="actions"><button className="primary" disabled={unavailable} onClick={()=>act(()=>rpc(`/commands/${command.id}/run`,{values,mode:'test'}))}><Play size={14}/>Test with review</button><button disabled={unavailable} onClick={()=>act(()=>rpc(`/commands/${command.id}/run`,{values,mode:'run'}))}>Run</button></div></section>
 <section className="card"><span className="eyebrow">02 / DEFINE SUCCESS</span><h3>What proves it worked?</h3><p className="small">A final outcome check is required for batches. Mimic waits for visible text on the result page.</p><label>Result selector<input placeholder="#confirmation" value={selector} onChange={e=>setSelector(e.target.value)}/></label><label>Expected text<input placeholder="Saved" value={expected} onChange={e=>setExpected(e.target.value)}/></label><button disabled={unavailable||!selector.trim()||!expected.trim()} onClick={()=>act(saveCheck)}><ShieldCheck size={14}/>Save outcome check</button><details><summary>Review actions & checkpoints</summary>{command.steps.map((s,i)=><label className="step" key={s.id}><span>{i+1}. {s.label}</span>{['click','press','check'].includes(s.type)&&<input type="checkbox" aria-label={`Review before ${s.label}`} checked={s.checkpoint} disabled={unavailable} onChange={e=>act(()=>rpc(`/commands/${command.id}`,{name:command.name,description:command.description,parameters:command.parameters,steps:command.steps.map(x=>x.id===s.id?{...x,checkpoint:e.target.checked}:x)},'PUT'))}/>}</label>)}<p className="small">Checked actions pause for your review in every row.</p></details></section>
 <section className="card"><span className="eyebrow">03 / BRING YOUR SPREADSHEET</span><h3>One workflow. A whole list.</h3><p className="small">Export Excel or Google Sheets as CSV. The file stays in your Chrome profile. Free: 3 rows per batch. Pro: up to 100.</p><label className="upload"><Table2 size={22}/><span>Choose a CSV file</span><input type="file" accept=".csv,text/csv" aria-label="Upload batch CSV" onChange={e=>{const f=e.target.files?.[0];if(f)act(()=>loadCsv(f));}}/></label>{command.sample&&<button className="back" onClick={()=>download('title,link,shelf\nA new idea,https://example.com/idea,Ideas\nResearch notes,https://example.com/research,Research\nClass reading,https://example.com/class,School\n','mimic-practice.csv')}>Download practice CSV</button>}
 {parsed&&<><h4>Map {parsed.rows.length} rows to workflow inputs</h4>{command.parameters.map(p=><label key={p.key}>{p.label}<select value={mapping[p.key]||''} onChange={e=>setMapping({...mapping,[p.key]:e.target.value})}><option value="">Choose a column</option>{parsed.headers.map(h=><option key={h}>{h}</option>)}</select></label>)}<div className="preview"><table><thead><tr>{parsed.headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{parsed.rows.slice(0,3).map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div><button className="primary wide" disabled={unavailable||command.parameters.some(p=>!mapping[p.key])} onClick={()=>act(async()=>{const b=await rpc('/batches',{commandId:command.id,csv,mapping});setBatchId(b.id);setSelected('');setTab('batches');})}>Review batch <ArrowUpRight size={15}/></button></>}
 </section></>}
 {tab==='batches'&&!batch&&!command&&<><div className="section-head"><h2>Your batches <span>{state.batches?.length||0}</span></h2></div>{!state.batches?.length&&<section className="empty"><Table2 size={30}/><h3>Your next hundred clicks,<br/>handled one row at a time.</h3><p>Choose a workflow, add an outcome check, and upload a CSV to create your first batch.</p><button onClick={()=>setTab('workflows')}>Choose a workflow</button></section>}{state.batches?.map(b=><button className="workflow" key={b.id} onClick={()=>setBatchId(b.id)}><span className="tile"><Table2 size={18}/></span><span><b>{b.name}</b><small>{b.rows.filter(r=>r.status==='verified').length}/{b.rows.length} verified · {b.status}</small></span><ArrowUpRight size={16}/></button>)}</>}
 {batch&&<><button className="back" onClick={()=>setBatchId('')}><ChevronLeft size={15}/>All batches</button><span className="eyebrow">{batch.status.toUpperCase()}</span><h2>{batch.name}</h2><div className="batch-stat"><strong>{batch.rows.filter(r=>r.status==='verified').length}<span> / {batch.rows.length}</span></strong><span>rows with observed outcomes</span></div><p className="small">Rows run sequentially. Failed or interrupted rows stop the batch. Confirming a row manually is recorded separately from an automated check.</p>{batch.error&&<p className="notice">{batch.error}</p>}<div className="actions">{state.batchActive===batch.id?<button disabled={busy} onClick={()=>act(()=>rpc(`/batches/${batch.id}/stop`,{}))}>Stop after this row</button>:<button className="primary" disabled={unavailable||batch.rows.some(r=>r.status==='review')||!batch.rows.some(r=>r.status==='pending')} onClick={()=>act(()=>rpc(`/batches/${batch.id}/start`,{}))}><Play size={14}/>{batch.status==='ready'?'Start batch':'Continue pending rows'}</button>}<button onClick={()=>download(csvResults(batch),'mimic-results.csv')}><Download size={14}/>Results</button></div>{batch.rows.map((r,i)=><Row key={r.id} row={r} index={i} busy={busy||!!state.batchActive} resolve={(decision,note)=>act(()=>rpc(`/batches/${batch.id}/resolve`,{rowId:r.id,decision,note}))}/>)}</>}
 {!command&&!batch&&state.runs.length>0&&<section className="card"><span className="eyebrow">LAST RUN</span><h3>{state.runs[0].commandName}</h3><b className={state.runs[0].status==='passed'?'success':''}>{state.runs[0].status}</b>{state.runs[0].outputs.map((o,i)=><p className="output" key={i}>{o.text}</p>)}{state.runs[0].error&&<p className="notice">{state.runs[0].error}</p>}</section>}
 <section className="pro-card"><Zap size={20}/><h3>Make busywork a smaller part of your day.</h3><p>Pro · $15/month<br/>100 rows per batch · 1,000 batch rows per calendar month · 100 saved workflows.</p><button onClick={()=>open('/account')}>{account.plan==='pro'?'Manage Pro':'Explore Pro'}<ArrowUpRight size={15}/></button></section>
 </main><footer><span><ShieldCheck size={12}/>Workflow data stays on this device</span><button onClick={()=>open('/privacy')}>Privacy</button></footer></>;
}
function Row({row,index,resolve,busy}){const [note,setNote]=useState('');return <section className={`row-result ${row.status}`}><div><b>Row {index+1}</b><span>{row.status==='verified'?<Check size={13}/>:null}{row.status}</span></div><details><summary>Inputs & observed result</summary><pre>{Object.entries(row.values).map(([k,v])=>`${k}: ${v}`).join('\n')}</pre>{row.output&&<p className="output">{row.output}</p>}</details>{row.note&&<p className="small">{row.note}</p>}{row.status==='review'&&<><label>What did you find on the website?<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={500} placeholder="I checked the record and…"/></label><div className="actions"><button disabled={busy||note.trim().length<5} onClick={()=>resolve('confirmed',note)}>Mark manually confirmed</button><button disabled={busy||note.trim().length<5} onClick={()=>resolve('skip',note)}>Skip this row</button></div></>}</section>;}
createRoot(document.getElementById('root')).render(<Panel/>);
